// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFF1E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLabel, 79);
    lv_obj_set_y(ui_timeLabel, 15);
    lv_label_set_text(ui_timeLabel, "00:00:00");
    lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_dateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateLabel, 120);
    lv_obj_set_y(ui_dateLabel, 68);
    lv_label_set_text(ui_dateLabel, "2021/12/12");

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
