// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFF1E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_kapigongde2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_kapigongde1_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_gongdeLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_gongdeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gongdeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gongdeLabel, 87);
    lv_obj_set_y(ui_gongdeLabel, -83);
    lv_obj_set_align(ui_gongdeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gongdeLabel, "功德+");
    lv_obj_set_style_text_font(ui_gongdeLabel, &ui_font_gongde, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gongdenumb = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_gongdenumb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gongdenumb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gongdenumb, 242);
    lv_obj_set_y(ui_gongdenumb, 63);
    lv_label_set_text(ui_gongdenumb, "0");
    lv_obj_set_style_text_font(ui_gongdenumb, &ui_font_gongde, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
