// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_dateLabel;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_gongdeLabel;
extern lv_obj_t * ui_gongdenumb;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_kapigongde2_png);    // assets\kapigongde2.png
LV_IMG_DECLARE(ui_img_kapigongde1_png);    // assets\kapigongde1.png
LV_IMG_DECLARE(ui_img_keyboard2_png);    // assets\keyboard2.png

LV_FONT_DECLARE(ui_font_clock);
LV_FONT_DECLARE(ui_font_clock2);
LV_FONT_DECLARE(ui_font_fans);
LV_FONT_DECLARE(ui_font_gongde);
LV_FONT_DECLARE(ui_font_market);
LV_FONT_DECLARE(ui_font_weatherWatch);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
